---
title: "Project 3"
author: "Nicholas Rubertone"
date: "3/30/2021"
output: pdf_document
---


```{r}
library(SASxport)
library(MASS)
library(FactoMineR)
library(factoextra)
library(VGAM)


library(tidyverse)
library(ggpubr)
library(rstatix)
library(broom)
```

```{r}
#Loading Data
data.health <- read.xport("HSQ_J.XPT")
data.conditions <- read.xport("MCQ_J.XPT")
data.demo <- read.xport("DEMO_J.XPT")
```

```{r}
#Getting IDs of people that appear in all three
all.ids <- c(data.health$SEQN, data.conditions$SEQN, data.demo$SEQN)
shared.ids <- as.numeric(names(table(all.ids)[table(all.ids)==3]))
```

```{r}
#Figure out which rows should be removed for having no condition data
namecols.conditions <- colnames(data.conditions.subset[,-1])
namecols.conditions.combined <- colnames(data.combined)[colnames(data.combined) %in% namecols.conditions]

data.find.no.conditions <- data.combined[,namecols.conditions.combined]

all.answered <- rep(NA, ncol(data.find.no.conditions))

for(i in 1:ncol(data.find.no.conditions)){
  all.answered[i] <- ifelse(sum(data.find.no.conditions[,i] != "Missing") == nrow(data.find.no.conditions), T, F)
}

all.answered.cols <- colnames(data.find.no.conditions)[which(all.answered)]

data.find.no.conditions.final <- data.find.no.conditions[,!(colnames(data.find.no.conditions) %in% all.answered.cols)]



no.conditions <- rep(NA, nrow(data.find.no.conditions.final))
for (i in 1:nrow(data.find.no.conditions.final)){
  data.fnc.temp <- as.vector(unlist(data.find.no.conditions.final[i,]))
  no.conditions[i] <- ifelse(sum(data.fnc.temp == "Missing") == length(data.fnc.temp), T, F)
}
sum(no.conditions)/nrow(data.find.no.conditions.final)

#View(data.find.no.conditions[no.conditions, ])

index<-rownames(data.find.no.conditions[no.conditions, ])
index<-as.integer(index)

```


```{r}
#Merge datasets
data.health.subset <- data.health[data.health$SEQN %in% shared.ids, c("SEQN", "HSD010")]
data.conditions.subset <- data.conditions[data.conditions$SEQN %in% shared.ids, ]
data.demo.subset <- data.demo[data.demo$SEQN %in% shared.ids, ]
data.demo.subset <-subset(data.demo, select=-c(SDDSRVYR,RIDSTATR,RIDAGEMN,RIDEXMON,RIDEXAGM,SIAINTRP,SIAPROXY,FIAPROXY,FIAINTRP,MIAPROXY,MIAINTRP,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA))

data.conditions.subset<-data.conditions.subset[! c(rownames(data.conditions.subset)%in% index),]

data.full.temp <- merge(data.health.subset, data.conditions.subset, by = "SEQN")
data.full <- merge(data.full.temp, data.demo.subset, by = "SEQN")
#Remove all other datasets, don't need them anymore

rm(data.health)
rm(data.health.subset)
rm(data.conditions)
rm(data.conditions.subset)
rm(data.demo)
rm(data.demo.subset)
```

## Removing Irrelevant Columns
```{r}
remove.cols <- c("MCQ025",
                 "MCQ035",
                 "MCQ040",
                 "MCQ050",
                 "MCD093",
                 "MCQ149",
                 "MCQ151",
                 "RHD018",
                 "MCD180A",
                 "MCD180N",
                 "MCD180B",
                 "MCD180C",
                 "MCD180D",
                 "MCD180E",
                 "MCD180F",
                 "MCQ170M",
                 "MCD180M",
                 "MCD180G",
                 "MCQ170K",
                 "MCD180K",
                 "MCD180L",
                 "MCQ170L",
                 "MCQ206",
                 "MCQ540",
                 "MCQ530")

#View subtitles for the removed ones
#View(data.full[,(colnames(data.full) %in% remove.cols)])

#Subset out removed columns
data.subcols <- data.full[, !(colnames(data.full) %in% remove.cols)]

#Find and remove columns with >= 80% NAs
remove.NAs <- apply(data.subcols, 2, function(x) sum(is.na(x))/nrow(data.subcols))
head(remove.NAs)

NAs.80plus <- names(which(remove.NAs >= 0.8))

#Final dataset
data.cols.final <- data.subcols[, !(colnames(data.subcols) %in% NAs.80plus)]
data.cols.final <- data.subcols[,-1]

data.final <- data.cols.final
#Set data types

data.num <- data.final[,colnames(data.final) %in% c("RIDAGEYR","DMDHHSIZ","DMDFMSIZ","DMDHHSZA",
                      "DMDHHSZB","DMDHHSZE","INDFMPIR")]

data.num<-as.data.frame(apply(data.num, 2, function(x) as.numeric(x)))


data.factor <- data.final[,!(colnames(data.final) %in% c("RIDAGEYR","DMDHHSIZ","DMDFMSIZ","DMDHHSZA", "DMDHHSZB","DMDHHSZE","INDFMPIR"))]

data.factor <- as.data.frame(apply(data.factor, 2, function(x) as.factor(x)))


#Remove NA

for(i in 1:ncol(data.factor)){
  tempcol <- data.factor[,i]
  tempcol[is.na(tempcol)] <- "Missing"
  data.factor[,i] <- tempcol
}

data.combined <- cbind(data.num, data.factor)
```

```{r}
#score loop
for(i in 1:nrow(data.combined)){
  if(data.combined$MCQ010[i]==1){
  data.combined$score[i]<-0.046
  }
  if(data.combined$MCQ010[i]!=1){
    data.combined$score[i]<-0
  }
  if(data.combined$MCQ195[i]==1){
     data.combined$score[i]<-sum(data.combined$score[i], 0.089)}
  
  if(data.combined$MCQ195[i]==2){
    data.combined$score[i]<-sum(data.combined$score[i], 0.338)}
  
  if(data.combined$MCQ195[i]==3){
    data.combined$score[i]<-sum(data.combined$score[i], 0.338)}
  
  if(data.combined$MCQ195[i]==4){
    data.combined$score[i]<-sum(data.combined$score[i], 0.338)}
  
  if(data.combined$MCQ160N[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.438)}
  
  if(data.combined$MCQ160B[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.085)}
  
  if(data.combined$MCQ160C[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.085)}
  
  if(data.combined$MCQ160D[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.093)}
  
  if(data.combined$MCQ160E[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.432)}
  
  if(data.combined$MCQ160F[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.309)}
  
  if(data.combined$MCQ160M[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.082)}
  
  if(data.combined$MCQ160O[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.392)}
  
  if(data.combined$MCQ053[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.024)}
  
  if(data.combined$MCQ510A[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.16)}
  
  if(data.combined$MCQ510B[i]==2){
    data.combined$score[i]<-sum(data.combined$score[i], 0.16)}
  
  if(data.combined$MCQ510C[i]==3){
    data.combined$score[i]<-sum(data.combined$score[i], 0.22)}
  
  if(data.combined$MCQ510D[i]==4){
    data.combined$score[i]<-sum(data.combined$score[i], 0.22)}
  
  if(data.combined$MCQ510E[i]==5){
    data.combined$score[i]<-sum(data.combined$score[i], 0.22)}
  
  if(data.combined$MCQ510F[i]==6){
    data.combined$score[i]<-sum(data.combined$score[i], 0.22)}
  
  if(data.combined$MCQ520[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.148)}
  
  if(data.combined$MCQ560[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.15)}
  
  if(data.combined$MCQ203[i]==1){
    data.combined$score[i]<-sum(data.combined$score[i], 0.387)}
  
  if(data.combined$MCQ230A[i]==10){
    data.combined$score[i]<-sum(data.combined$score[i], 0.293)}
  
  if(data.combined$MCQ230A[i]==11){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==12){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==13){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==14){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==15){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==16){
    data.combined$score[i]<-sum(data.combined$score[i], 0.26)}
  
  if(data.combined$MCQ230A[i]==17){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==18){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==19){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==20){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==21){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==22){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==23){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==24){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==25){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==26){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==27){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==28){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==29){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==30){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==31){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==32){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==33){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==34){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==35){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==36){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==37){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==38){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230A[i]==39){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==10){
    data.combined$score[i]<-sum(data.combined$score[i], 0.293)}
  
  if(data.combined$MCQ230B[i]==11){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==12){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==13){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==14){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==15){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==16){
    data.combined$score[i]<-sum(data.combined$score[i], 0.26)}
  
  if(data.combined$MCQ230B[i]==17){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==18){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==19){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==20){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==21){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==22){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==23){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==24){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==25){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==26){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==27){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==28){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==29){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==30){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==31){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==32){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==33){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==34){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==35){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==36){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==37){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==38){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230B[i]==39){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}

  if(data.combined$MCQ230C[i]==10){
    data.combined$score[i]<-sum(data.combined$score[i], 0.293)}
  
  if(data.combined$MCQ230C[i]==11){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==12){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==13){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==14){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==15){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==16){
    data.combined$score[i]<-sum(data.combined$score[i], 0.26)}
  
  if(data.combined$MCQ230C[i]==17){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==18){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==19){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==20){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==21){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==22){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==23){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==24){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==25){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==26){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==27){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==28){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==29){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==30){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==31){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==32){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==33){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==34){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==35){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==36){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==37){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==38){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
  if(data.combined$MCQ230C[i]==39){
    data.combined$score[i]<-sum(data.combined$score[i], 0.332)}
  
}
?quantile
hist()
quantile(data.combined$score, probs = c(0, 0.2, 0.4, 0.6, 0.8,1), na.rm=T)
data.combined$score_quant<-quantile(log(data.combined$score), probs=seq(0,1, 0.2))


hist(data.combined$score)
```

```{r}
#remove refused or don't know answers
#which(data.combined$HSD010==7 | data.combined$HSD010==9)
data.combined<-data.combined[-c(83, 5303, 6966),]

#remove missing
#which(data.combined$HSD010=="Missing")
data.combined.test<-data.combined[-c(which(data.combined$HSD010=="Missing")),]
```

```{r}
data.test <- data.combined
data.test$HSD010[data.test$HSD010 == "Missing"] <- NA
data.test$HSD010 <- as.factor(data.test$HSD010)
table(data.test$HSD010)


vglm<-vglm(HSD010 ~ score+ RIDRETH3, data = data.combined.test, family=propodds)
summary(vglm)

lm1<-lm(score ~ factor(HSD010):factor(RIDRETH3) -1,data = data.combined.test)
summary(lm1)

table(data.combined$RIDRETH3)

mod2 <- as.data.frame(summary(lm1)$coefficients)
mod2$sig <- NA
for(i in 1:nrow(mod2)){
  if(mod2[i, "Pr(>|t|)"] <=0.001){
    mod2[i, "sig"] <- "***"
  }else if(mod2[i, "Pr(>|t|)"] <= 0.01){
    mod2[i, "sig"] <- "**"
  }else if(mod2[i, "Pr(>|t|)"] <= 0.05){
    mod2[i, "sig"] <- "*"
  }else if(mod2[i, "Pr(>|t|)"] <= 0.1){
    mod2[i, "sig"] <- "."
  }else if(mod2[i, "Pr(>|t|)"] > 0.1){
    mod2[i, "sig"] <- ""
  }
}

View(mod2)

plot(density(data.combined$score[data.combined$HSD010=="5"]))
plot(density(data.combined$score))
ggplot(data=data.combined, aes())+


plot(data.combined.test$score, data.combined.test$HSD010)




lm1_valid<-lm(score ~ factor(PHSTAT_A):factor(HISPALLP_A) ,data = valid_data_df)
summary(lm1_valid)

test_lm <- polr(HSD010 ~ score+ factor(RIDRETH3) + factor(RIAGENDR), data = data.test, Hess=T)


ctable <- coef(summary(lm))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

## combined table
ctable <- cbind(ctable, "p value" = p)
```

```{r}
data.noout <- data.factor[,-which(colnames(data.factor) == "HSD010")]
data.noout <- data.noout[,!(colnames(data.noout) %in% colnames(data.demo))]

mca.test <- MCA(data.noout, ncp = 10)

#mca.eig <- get_eigenvalue(mca.test)
#head(mca.eig)

mcavar <- get_mca_var(mca.test)

#mcavar$cos2

fviz_screeplot(mca.test, addlabels = TRUE, ylim = c(0, 45))



```

## NHIS Data
```{r}
valid_data<-read.csv("adult19.csv")
#VARIABLES
var_names<-c("PHSTAT_A","HISPALLP_A",
  "HISDETP_A",
  "INCGRP_A",
  "URBRRL",
  "ASEV_A",
  "ARTHEV_A",
 "CHDEV_A",
 "ANGEV_A",
 "MIEV_A",
 "STREV_A",
 "COPDEV_A",
 "PAIAPG3M_A",
"BLADDCAN_A",
"BLOODCAN_A",
"BONECAN_A",
"BRAINCAN_A",
"BREASCAN_A",
"CERVICEV_A",
"COLONCAN_A",
"ESOPHCAN_A",
"GALLBCAN_A",
"LARYNCAN_A",
"LEUKECAN_A",
"LIVERCAN_A",
"LUNGCAN_A",
"LYMPHCAN_A",
"MELANCAN_A",
"MOUTHCAN_A",
"OVARYCAN_A",
"PANCRCAN_A",
"PROSTCAN_A",
"RECTUCAN_A",
"SKNNMCAN_A",
"SKNDKCAN_A",
"STOMACAN_A",
"THYROCAN_A",
"UTERUCAN_A")

valid_data_df<-valid_data[,var_names]
#fix ethnicity to match original data
for(i in 1:nrow(valid_data_df)){
  if(valid_data_df$HISPALLP_A[i]==2){
    valid_data_df$HISPALLP_A[i]<-3
    next
  }
   if(valid_data_df$HISPALLP_A[i]==3){
    valid_data_df$HISPALLP_A[i]<-4
    next
   }
  if(valid_data_df$HISPALLP_A[i]==4){
    valid_data_df$HISPALLP_A[i]<-6
    next
  }
  if(valid_data_df$HISPALLP_A[i]==5){
    valid_data_df$HISPALLP_A[i]<-7
    next
  }
  if(valid_data_df$HISPALLP_A[i]==6){
    valid_data_df$HISPALLP_A[i]<-7
    next
  }
  if(valid_data_df$HISPALLP_A[i]==7){
    valid_data_df$HISPALLP_A[i]<-7
    next
  }
}
valid_data_df$HISPALLP_A[which(valid_data_df$HISDETP_A==1)]<-1
valid_data_df$HISPALLP_A[which(valid_data_df$HISDETP_A==2)]<-2

table(valid_data_df$HISPALLP_A)

#remove NA
remove.NAs <- apply(valid_data_df, 2, function(x) sum(is.na(x))/nrow(valid_data_df))
head(remove.NAs)

NAs.80plus <- names(which(remove.NAs >= 0.8))

#valid_data_df <- valid_data_df[, !(colnames(valid_data_df) %in% NAs.80plus)]


valid_data_df <- as.data.frame(apply(valid_data_df, 2, function(x) as.factor(x)))


for(i in 1:ncol(valid_data_df)){
  tempcol <- valid_data_df[,i]
  tempcol[is.na(tempcol)] <- "Missing"
  valid_data_df[,i] <- tempcol
}
```

```{r}
for(i in 1:nrow(valid_data_df)){
  if(valid_data_df$ASEV_A[i]==1){
  valid_data_df$score[i]<-0.046}
  if(valid_data_df$ASEV_A[i]!=1){
    valid_data_df$score[i]<-0}
  if(valid_data_df$ARTHEV_A[i]==1){
     valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.288)}
  if(valid_data_df$CHDEV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.085)}
  if(valid_data_df$ANGEV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.093)}
  if(valid_data_df$MIEV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.432)}
  if(valid_data_df$STREV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.309)}
  if(valid_data_df$COPDEV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.392)}
  if(valid_data_df$PAIAPG3M_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.148)}
  if(valid_data_df$BLADDCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.293)}
  if(valid_data_df$BLOODCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$BONECAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$BRAINCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$BREASCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$CERVICEV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$COLONCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.26)}
  if(valid_data_df$ESOPHCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$GALLBCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$LARYNCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$LEUKECAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$LIVERCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$LUNGCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$LYMPHCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$MELANCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$MOUTHCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$OVARYCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$PANCRCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$PROSTCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$RECTUCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$SKNNMCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$SKNDKCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$STOMACAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$THYROCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$UTERUCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
}


plot(density(valid_data_df$score[valid_data_df$PHSTAT_A=="4" & valid_data_df$INCGRP==1]), xlim=c(0,2.5), col="red")
abline(v=mean(valid_data_df$score[valid_data_df$PHSTAT_A=="4" & valid_data_df$INCGRP==1]),col="red")
lines(density(valid_data_df$score[valid_data_df$PHSTAT_A=="4" & valid_data_df$INCGRP==2]),xlim=c(0,2.5), col="blue")
abline(v=mean(valid_data_df$score[valid_data_df$PHSTAT_A=="4" & valid_data_df$INCGRP==2]),col="blue")
lines(density(valid_data_df$score[valid_data_df$PHSTAT_A=="4" & valid_data_df$INCGRP==3]),xlim=c(0,2.5),col="green")
abline(v=mean(valid_data_df$score[valid_data_df$PHSTAT_A=="4" & valid_data_df$INCGRP==3]),col="green")
lines(density(valid_data_df$score[valid_data_df$PHSTAT_A=="4" & valid_data_df$INCGRP==4]),xlim=c(0,2.5), col="pink")
abline(v=mean(valid_data_df$score[valid_data_df$PHSTAT_A=="4" & valid_data_df$INCGRP==4]),col="pink")
lines(density(valid_data_df$score[valid_data_df$PHSTAT_A=="4" & valid_data_df$INCGRP==5]),xlim=c(0,2.5), col="black")
abline(v=mean(valid_data_df$score[valid_data_df$PHSTAT_A=="4" & valid_data_df$INCGRP==5]),col="black")
legend("topright", legend = c("0-35000", "35000-50000", "50000-75000", "75000-99000", "100000+"), col = c("red","blue", "green", "pink","black"), lty = 1)


plot(density(valid_data_df$score[valid_data_df$PHSTAT_A=="5" & valid_data_df$INCGRP==5]),xlim=c(0,2.5), col="black")
abline(v=mean(valid_data_df$score[valid_data_df$PHSTAT_A=="5" & valid_data_df$HISPALLP_A==5]),col="black")

lines(density(valid_data_df$score[valid_data_df$PHSTAT_A=="1" & valid_data_df$HISPALLP_A==5]),xlim=c(0,2.5), col="black")

plot(density(valid_data_df$score),xlim=c(0,2.5))

boxplot(valid_data_df$score~valid_data_df$PHSTAT_A)

boxplot(data.combined.test$score~data.combined.test$HSD010)


plot(density(valid_data_df$score))
lines()


```

```{r}
lm1<-lm(score ~ PHSTAT_A:INCGRP_A -1,data = valid_data_df)
mod2 <- as.data.frame(summary(lm1)$coefficients)
mod2$sig <- NA
for(i in 1:nrow(mod2)){
  if(mod2[i, "Pr(>|t|)"] <=0.001){
    mod2[i, "sig"] <- "***"
  }else if(mod2[i, "Pr(>|t|)"] <= 0.01){
    mod2[i, "sig"] <- "**"
  }else if(mod2[i, "Pr(>|t|)"] <= 0.05){
    mod2[i, "sig"] <- "*"
  }else if(mod2[i, "Pr(>|t|)"] <= 0.1){
    mod2[i, "sig"] <- "."
  }else if(mod2[i, "Pr(>|t|)"] > 0.1){
    mod2[i, "sig"] <- ""
  }
}
valid_data_df$INCGRP_A
View(mod2)

quant<-quantile(valid_data_df$score, seq(0,1, 0.2))
quant[[5]]

for(i in 1:nrow(valid_data_df)){
  if(valid_data_df$score[i] <= quant[[2]]){
    valid_data_df$score_quant[i]<-1
  }
  if(valid_data_df$score[i] <= quant[[3]] & valid_data_df$score[i] > quant[[2]]){
    valid_data_df$score_quant[i]<-2
  }
  if(valid_data_df$score[i] <= quant[[4]] & valid_data_df$score[i] > quant[[3]]){
    valid_data_df$score_quant[i]<-3
  }
  if(valid_data_df$score[i] <= quant[[5]] & valid_data_df$score[i] > quant[[4]]){
    valid_data_df$score_quant[i]<-4
  }
  if(valid_data_df$score[i] <= quant[[6]] & valid_data_df$score[i] > quant[[5]]){
    valid_data_df$score_quant[i]<-5
  }
}

for(i in 1:nrow(valid_data_df)){
  if(valid_data_df$score_quant[i]==valid_data_df$PHSTAT_A[i]){
    valid_data_df$percep_true[i]<-1
  }
  else{valid_data_df$percep_true[i]<-0}
}
finaltab<-matrix(NA, nrow=5, ncol=7)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
    test<-valid_data_df$percep_true[valid_data_df$INCGRP_A==i & valid_data_df$PHSTAT_A==unique(sort(valid_data_df$PHSTAT_A, decreasing=F))[x]] 
    vec1<-sum(test)/length(test)
    finaltab[i,x]<-vec1
  }
}

#finaltab<-finaltab[,-c(6,7)]
rownames(finaltab) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(finaltab) <- c("Excellent","Very Good","Good","Fair","Poor", "Don't Know", "Missing")
finaltab<-round((finaltab*100), 2)
finaltab

finaltab_wrong<-matrix(NA, nrow=5, ncol=7)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
    test<-valid_data_df$percep_true[valid_data_df$INCGRP_A==i & valid_data_df$PHSTAT_A==unique(sort(valid_data_df$PHSTAT_A, decreasing=F))[x]] 
    vec1<-length(which(test==0))/length(test)
    finaltab_wrong[i,x]<-vec1
  }
}

#finaltab_wrong<-finaltab_wrong[,-c(6,7)]
rownames(finaltab_wrong) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(finaltab_wrong) <- c("Excellent","Very Good","Good","Fair","Poor", "Don't Know", "Missing")
finaltab_wrong<-round((finaltab_wrong*100), 2)
finaltab_wrong


finaltab_100<-matrix(NA, nrow=5, ncol=7)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
    test<-valid_data_df$percep_true[valid_data_df$INCGRP_A==i & valid_data_df$PHSTAT_A==unique(sort(valid_data_df$PHSTAT_A, decreasing=F))[x]] 
    vec1<-sum(test)/nrow(valid_data_df[valid_data_df$INCGRP_A==i,])
    finaltab_100[i,x]<-vec1
  }
}

finaltab_100<-finaltab_100[,-c(6,7)]
rownames(finaltab_100) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(finaltab_100) <- c("Excellent","Very Good","Good","Fair","Poor","Don't Know", "Missing")
finaltab_100<-round((finaltab_100*100), 2)
finaltab_100

i<-1
x<-1
finaltab_100_wrong<-matrix(NA, nrow=5, ncol=7)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
    test<-valid_data_df$percep_true[valid_data_df$INCGRP_A==i & valid_data_df$PHSTAT_A==unique(sort(valid_data_df$PHSTAT_A, decreasing=F))[x]] 
    vec1<-length(which(test==0))/nrow(valid_data_df[valid_data_df$INCGRP_A==i,])
    finaltab_100_wrong[i,x]<-vec1
  }
}
sum(test)
finaltab_100_wrong<-finaltab_100_wrong[,-c(6,7)]
rownames(finaltab_100_wrong) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(finaltab_100_wrong) <- c("Excellent","Very Good","Good","Fair","Poor", "Don't Know", "Missing")
finaltab_100_wrong<-round((finaltab_100_wrong*100), 2)
finaltab_100_wrong

finaltab_100_wrong
finaltab_100
sum(finaltab_100_wrong[5,],finaltab_100[5,])


#model validation to determine score var
#based on score, what did you put for each income category
#proportion of people
#should capture perceived health not just counts
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```







