---
title: "Project 3"
author: "Nicholas Rubertone & Filippo Ravalli"
date: "4/19/2021"
output: pdf_document
---

## Libraries
```{r}
library(ggplot2) 
library(tidyverse)
library(ggpubr) 
library(rstatix)
library(broom)
library(caret)
library(e1071)
```


## Load in data and processing
```{r}
valid_data<-read.csv("adult19.csv")
#VARIABLES
var_names<-c("PHSTAT_A",
  "INCGRP_A",
  "ASEV_A",
  "ARTHEV_A",
 "CHDEV_A",
 "ANGEV_A",
 "MIEV_A",
 "STREV_A",
 "COPDEV_A",
 "PAIAPG3M_A",
"BLADDCAN_A",
"BLOODCAN_A",
"BONECAN_A",
"BRAINCAN_A",
"BREASCAN_A",
"CERVICEV_A",
"COLONCAN_A",
"ESOPHCAN_A",
"GALLBCAN_A",
"LARYNCAN_A",
"LEUKECAN_A",
"LIVERCAN_A",
"LUNGCAN_A",
"LYMPHCAN_A",
"MELANCAN_A",
"MOUTHCAN_A",
"OVARYCAN_A",
"PANCRCAN_A",
"PROSTCAN_A",
"RECTUCAN_A",
"SKNNMCAN_A",
"SKNDKCAN_A",
"STOMACAN_A",
"THYROCAN_A",
"UTERUCAN_A")

valid_data_df<-valid_data[,var_names]




valid_data_df <- as.data.frame(apply(valid_data_df, 2, function(x) as.factor(x)))

names(which(colSums(is.na(valid_data_df)) > 0))

for(i in 1:ncol(valid_data_df)){
  tempcol <- valid_data_df[,i]
  tempcol[is.na(tempcol)] <- "Missing"
  valid_data_df[,i] <- tempcol
}

#Remove rows where perceived health is not 1:5
valid_data_df<-valid_data_df[which(valid_data_df$PHSTAT_A != 7),]
valid_data_df<-valid_data_df[which(valid_data_df$PHSTAT_A != 9),]
```

#Assign Score
```{r}
for(i in 1:nrow(valid_data_df)){
  if(valid_data_df$ASEV_A[i]==1){
  valid_data_df$score[i]<-0.046}
  if(valid_data_df$ASEV_A[i]!=1){
    valid_data_df$score[i]<-0}
  if(valid_data_df$ARTHEV_A[i]==1){
     valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.288)}
  if(valid_data_df$CHDEV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.085)}
  if(valid_data_df$ANGEV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.093)}
  if(valid_data_df$MIEV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.432)}
  if(valid_data_df$STREV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.309)}
  if(valid_data_df$COPDEV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.392)}
  if(valid_data_df$PAIAPG3M_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.148)}
  if(valid_data_df$BLADDCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.293)}
  if(valid_data_df$BLOODCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$BONECAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$BRAINCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$BREASCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$CERVICEV_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$COLONCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.26)}
  if(valid_data_df$ESOPHCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$GALLBCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$LARYNCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$LEUKECAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$LIVERCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$LUNGCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$LYMPHCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$MELANCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$MOUTHCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$OVARYCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$PANCRCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$PROSTCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$RECTUCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$SKNNMCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$SKNDKCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$STOMACAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$THYROCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
  if(valid_data_df$UTERUCAN_A[i]==1){
    valid_data_df$score[i]<-sum(valid_data_df$score[i], 0.332)}
}

(length(which(valid_data_df$score>1.5))/nrow(valid_data_df))*100
```

#Assign & Create score quantiles
```{r}
quant<-quantile(valid_data_df$score, seq(0,1, 0.2))
#quant[[5]]
#assign quant to score
for(i in 1:nrow(valid_data_df)){
  if(valid_data_df$score[i] <= quant[[2]]){
    valid_data_df$score_quant[i]<-1
  }
  if(valid_data_df$score[i] <= quant[[3]] & valid_data_df$score[i] > quant[[2]]){
    valid_data_df$score_quant[i]<-2
  }
  if(valid_data_df$score[i] <= quant[[4]] & valid_data_df$score[i] > quant[[3]]){
    valid_data_df$score_quant[i]<-3
  }
  if(valid_data_df$score[i] <= quant[[5]] & valid_data_df$score[i] > quant[[4]]){
    valid_data_df$score_quant[i]<-4
  }
  if(valid_data_df$score[i] <= quant[[6]] & valid_data_df$score[i] > quant[[5]]){
    valid_data_df$score_quant[i]<-5
  }
}

#if score matches perceived health
for(i in 1:nrow(valid_data_df)){
  if(valid_data_df$score_quant[i]==valid_data_df$PHSTAT_A[i]){
    valid_data_df$percep_true[i]<-1
  }
  else{valid_data_df$percep_true[i]<-0}
}

#if score is +/- 1 of perceieved
for(i in 1:nrow(valid_data_df)){
  if(abs(valid_data_df$score_quant[i] - as.numeric(valid_data_df$PHSTAT_A[i]))<2){
    valid_data_df$percep_true_2[i]<-1
  }
  else{valid_data_df$percep_true_2[i]<-0}
}
```



#Model
```{r}
lm1<-lm(score ~ PHSTAT_A:INCGRP_A,data = valid_data_df)
mod2 <- as.data.frame(summary(lm1)$coefficients)
mod2$sig <- NA
for(i in 1:nrow(mod2)){
  if(mod2[i, "Pr(>|t|)"] <=0.001){
    mod2[i, "sig"] <- "***"
  }else if(mod2[i, "Pr(>|t|)"] <= 0.01){
    mod2[i, "sig"] <- "**"
  }else if(mod2[i, "Pr(>|t|)"] <= 0.05){
    mod2[i, "sig"] <- "*"
  }else if(mod2[i, "Pr(>|t|)"] <= 0.1){
    mod2[i, "sig"] <- "."
  }else if(mod2[i, "Pr(>|t|)"] > 0.1){
    mod2[i, "sig"] <- ""
  }
}
#valid_data_df$INCGRP_A
View(mod2)
write.csv(mod2, "lm_output.csv")
summary(lm1)

lm2<-lm(score ~ PHSTAT_A,data = valid_data_df)
summary(lm2)

lm3<-lm(score ~ INCGRP_A,data = valid_data_df)
summary(lm3)
```


## Validation Loop
```{r}
n <- 100

vloop.exact.value <- rep(NA, n)
vloop.approx.value <- rep(NA, n)
vloop.approx.income.total <- list()
vloop.exact.income.total <- list()
vloop.income.distribution <- list()
vloop.exact.income.score <- list()
vloop.approx.income.score <- list()

for (q in 1:n){
	valid_data_df.test <- valid_data_df[as.numeric(valid_data_df$PHSTAT_A) %in% c(1,2,3,4,5), ]

	partition.rule <- createDataPartition(valid_data_df.test$score, p = 0.8, list = F)
	training.data <- valid_data_df.test[partition.rule, ]
	testing.data <- valid_data_df.test[-partition.rule, ]
	
	split.rule <- trainControl(method="repeatedcv", number = 5, repeats = 2, classProbs = F, summaryFunction = defaultSummary)	
	glmModel <- suppressWarnings(train(score ~ PHSTAT_A:INCGRP_A, data = training.data, trControl = split.rule, method = "glm", preProc = c("center", "scale"), metric = "RMSE", 	na.action = na.omit))
	
	suppressWarnings(glmTest <- predict(glmModel, newdata = testing.data))
	

	
	
	score.quants <-quantile(valid_data_df$score, seq(0,1, 0.2))
	test.score.categories <- ifelse(testing.data$score <= score.quants[2], 1, 
	                                ifelse(testing.data$score > score.quants[2] & testing.data$score <= score.quants[3], 2, 
	                                       ifelse(testing.data$score > score.quants[3] & testing.data$score <= score.quants[4], 3,
	                                              ifelse(testing.data$score > score.quants[4] & testing.data$score <= score.quants[5], 4,
	                                                     ifelse(testing.data$score > score.quants[5], 5, NA)))))
	
	
	pred.score.quants <- quantile(valid_data_df$score, seq(0,1, 0.2))
	pred.score.categories <- ifelse(glmTest <= pred.score.quants[2], 1, 
	                                ifelse(glmTest > pred.score.quants[2] & glmTest <= pred.score.quants[3], 2, 
	                                       ifelse(glmTest > pred.score.quants[3] & glmTest <= pred.score.quants[4], 3,
	                                              ifelse(glmTest > pred.score.quants[4] & glmTest <= pred.score.quants[5], 4,
	                                                     ifelse(glmTest > pred.score.quants[5], 5, NA)))))
	

	
	
	
	
	raw.pred.classification <- table(testing.data$INCGRP_A, test.score.categories)
	prop.pred.classification <- raw.pred.classification
	colnames(prop.pred.classification) <- c("Excellent","Very Good","Good","Fair","Poor")
	rownames(prop.pred.classification) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
	
	for(i in 1:5){
	  prop.pred.classification[i, ] <- prop.pred.classification[i, ]/sum(prop.pred.classification[i, ])
	}
	
	#What was the breakdown of the predictions by health status and income
	vloop.income.distribution[[q]] <- prop.pred.classification

	
	
	
	
	
	accuracy.df <- data.frame(test.score.categories, pred.score.categories, as.numeric(pred.score.categories-test.score.categories), as.numeric((pred.score.categories-test.score.categories) %in% c(0, -1, 1)), 	testing.data$INCGRP_A)
	colnames(accuracy.df) <- c("True.Score", "Predicted.Score", "Exact.Correct", "Approx.Correct", "Income.Group")
	
	
	#General Accuracy
	vloop.exact.value[q] <- mean(accuracy.df$Exact.Correct)
	vloop.approx.value[q] <-mean(accuracy.df$Approx.Correct)

  

	
	#Accuracy by Income
	
	test.accuracy.mat.approx.total <- matrix(rep(NA,5), nrow = 5, ncol = 1)
	colnames(test.accuracy.mat.approx.total) <- c("Total Accuracy")
	rownames(test.accuracy.mat.approx.total) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
	
	for(i in 1:5){
	  test.accuracy.mat.approx.total[i,1] <- mean(accuracy.df[accuracy.df$Income.Group == i, "Approx.Correct"])
	}
	
	vloop.approx.income.total[[q]] <- test.accuracy.mat.approx.total

	
	test.accuracy.mat.exact.total <- matrix(rep(NA,5), nrow = 5, ncol = 1)
	colnames(test.accuracy.mat.exact.total) <- c("Total Accuracy")
	rownames(test.accuracy.mat.exact.total) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
	
	for(i in 1:5){
	  test.accuracy.mat.exact.total[i,1] <- mean(accuracy.df[accuracy.df$Income.Group == i, "Exact.Correct"])
	}
	
	vloop.exact.income.total[[q]] <- test.accuracy.mat.exact.total
  
  
  
	
	
  #Stratified Accuracy
  test.accuracy.mat.exact <- matrix(rep(NA,25), nrow = 5, ncol = 5)
	colnames(test.accuracy.mat.exact) <- c("Excellent","Very Good","Good","Fair","Poor")
	rownames(test.accuracy.mat.exact) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
	
	for(i in 1:5){
	  for(j in 1:5){
	    test.accuracy.mat.exact[i,j] <- mean(accuracy.df[accuracy.df$Income.Group == i & accuracy.df$True.Score == j, "Exact.Correct"])
	  }
	}
	
	test.accuracy.mat.approx <- matrix(rep(NA,25), nrow = 5, ncol = 5)
	colnames(test.accuracy.mat.approx) <- c("Excellent","Very Good","Good","Fair","Poor")
	rownames(test.accuracy.mat.approx) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
	
	for(i in 1:5){
	  for(j in 1:5){
	    test.accuracy.mat.approx[i,j] <- mean(accuracy.df[accuracy.df$Income.Group == i & accuracy.df$True.Score == j, "Approx.Correct"])
	  }
	}

		
	#What was the exact prediction accuracy
	vloop.exact.income.score[[q]] <- test.accuracy.mat.exact
	
	#What was the approximate  prediction accuracy (+/- 1)
	vloop.approx.income.score[[q]] <- test.accuracy.mat.approx

  
	
	
}
```

## Valdation Visualizations
```{r}
mean(vloop.exact.value)
mean(vloop.approx.value) 
vloop.valid.approx.income.total <- Reduce("+", vloop.approx.income.total) / length(vloop.approx.income.total)
vloop.valid.exact.income.total <- Reduce("+", vloop.exact.income.total) / length(vloop.exact.income.total)
vloop.valid.income.distribution <- Reduce("+", vloop.income.distribution) / length(vloop.income.distribution)
vloop.valid.exact.income.score <- Reduce("+", vloop.exact.income.score) / length(vloop.exact.income.score)
vloop.valid.approx.income.score <- Reduce("+", vloop.approx.income.score) / length(vloop.approx.income.score)

write.table(round(vloop.valid.approx.income.total*100,2), "clipboard", sep="\t", col.names = T)
write.table(round(vloop.valid.approx.income.score*100,2), "clipboard", sep="\t", col.names = T)

ttable <- as.matrix(vloop.valid.income.distribution) * vloop.valid.approx.income.score
rowSums(ttable)
vloop.valid.approx.income.total

```

## Reduced Model Comparison
```{r}
n <- 100

vloop.exact.value.null <- rep(NA, n)
vloop.approx.value.null <- rep(NA, n)
vloop.approx.income.total.null <- list()
vloop.income.distribution.null <- list()
vloop.exact.income.score.null <- list()
vloop.approx.income.score.null <- list()
vloop.exact.income.total.null <- list()

for (q in 1:n){
	valid_data_df.test <- valid_data_df[as.numeric(valid_data_df$PHSTAT_A) %in% c(1,2,3,4,5), ]

	partition.rule <- createDataPartition(valid_data_df.test$score, p = 0.8, list = F)
	training.data <- valid_data_df.test[partition.rule, ]
	testing.data <- valid_data_df.test[-partition.rule, ]
	
	split.rule <- trainControl(method="repeatedcv", number = 5, repeats = 2, classProbs = F, summaryFunction = defaultSummary)	
  glmModel <- suppressWarnings(train(score ~ INCGRP_A, data = training.data, trControl = split.rule, method = "glm", preProc = c("center", "scale"), metric = "RMSE", 	na.action = na.omit))
  
	glmTest <- predict(glmModel, newdata = testing.data)
	

	
	
	score.quants <-quantile(valid_data_df$score, seq(0,1, 0.2))
	test.score.categories <- ifelse(testing.data$score <= score.quants[2], 1, 
	                                ifelse(testing.data$score > score.quants[2] & testing.data$score <= score.quants[3], 2, 
	                                       ifelse(testing.data$score > score.quants[3] & testing.data$score <= score.quants[4], 3,
	                                              ifelse(testing.data$score > score.quants[4] & testing.data$score <= score.quants[5], 4,
	                                                     ifelse(testing.data$score > score.quants[5], 5, NA)))))
	
	
	pred.score.quants <- quantile(valid_data_df$score, seq(0,1, 0.2))
	pred.score.categories <- ifelse(glmTest <= pred.score.quants[2], 1, 
	                                ifelse(glmTest > pred.score.quants[2] & glmTest <= pred.score.quants[3], 2, 
	                                       ifelse(glmTest > pred.score.quants[3] & glmTest <= pred.score.quants[4], 3,
	                                              ifelse(glmTest > pred.score.quants[4] & glmTest <= pred.score.quants[5], 4,
	                                                     ifelse(glmTest > pred.score.quants[5], 5, NA)))))
	

	
	
	
	
	raw.pred.classification <- table(testing.data$INCGRP_A, test.score.categories)
	prop.pred.classification <- raw.pred.classification
	colnames(prop.pred.classification) <- c("Excellent","Very Good","Good","Fair","Poor")
	rownames(prop.pred.classification) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
	
	for(i in 1:5){
	  prop.pred.classification[i, ] <- prop.pred.classification[i, ]/sum(prop.pred.classification[i, ])
	}
	
	#What was the breakdown of the predictions by health status and income
	vloop.income.distribution.null[[q]] <- prop.pred.classification

	
	
	
	
	
	accuracy.df <- data.frame(test.score.categories, pred.score.categories, as.numeric(pred.score.categories-test.score.categories), as.numeric((pred.score.categories-test.score.categories) %in% c(0, -1, 1)), 	testing.data$INCGRP_A)
	colnames(accuracy.df) <- c("True.Score", "Predicted.Score", "Exact.Correct", "Approx.Correct", "Income.Group")
	
	
	#General Accuracy
	vloop.exact.value.null[q] <- mean(accuracy.df$Exact.Correct)
	vloop.approx.value.null[q] <-mean(accuracy.df$Approx.Correct)

  

	
	#Accuracy by Income
	
	test.accuracy.mat.approx.total <- matrix(rep(NA,5), nrow = 5, ncol = 1)
	colnames(test.accuracy.mat.approx.total) <- c("Total Accuracy")
	rownames(test.accuracy.mat.approx.total) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
	
	for(i in 1:5){
	  test.accuracy.mat.approx.total[i,1] <- mean(accuracy.df[accuracy.df$Income.Group == i, "Approx.Correct"])
	}
	
	vloop.approx.income.total.null[[q]] <- test.accuracy.mat.approx.total

	
	test.accuracy.mat.exact.total <- matrix(rep(NA,5), nrow = 5, ncol = 1)
	colnames(test.accuracy.mat.exact.total) <- c("Total Accuracy")
	rownames(test.accuracy.mat.exact.total) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
	
	for(i in 1:5){
	  test.accuracy.mat.exact.total[i,1] <- mean(accuracy.df[accuracy.df$Income.Group == i, "Exact.Correct"])
	}
	
	vloop.exact.income.total.null[[q]] <- test.accuracy.mat.exact.total
  
  
  
	
	
  #Stratified Accuracy
  test.accuracy.mat.exact <- matrix(rep(NA,25), nrow = 5, ncol = 5)
	colnames(test.accuracy.mat.exact) <- c("Excellent","Very Good","Good","Fair","Poor")
	rownames(test.accuracy.mat.exact) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
	
	for(i in 1:5){
	  for(j in 1:5){
	    test.accuracy.mat.exact[i,j] <- mean(accuracy.df[accuracy.df$Income.Group == i & accuracy.df$True.Score == j, "Exact.Correct"])
	  }
	}
	
	test.accuracy.mat.approx <- matrix(rep(NA,25), nrow = 5, ncol = 5)
	colnames(test.accuracy.mat.approx) <- c("Excellent","Very Good","Good","Fair","Poor")
	rownames(test.accuracy.mat.approx) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
	
	for(i in 1:5){
	  for(j in 1:5){
	    test.accuracy.mat.approx[i,j] <- mean(accuracy.df[accuracy.df$Income.Group == i & accuracy.df$True.Score == j, "Approx.Correct"])
	  }
	}

		
	#What was the exact prediction accuracy
	vloop.exact.income.score.null[[q]] <- test.accuracy.mat.exact
	
	#What was the approximate  prediction accuracy (+/- 1)
	vloop.approx.income.score.null[[q]] <- test.accuracy.mat.approx

  
	
	
}
```

## Reduced Model Visualizations
```{r}
mean(vloop.exact.value.null)
mean(vloop.approx.value.null) 
vloop.valid.approx.income.total.null <- Reduce("+", vloop.approx.income.total.null) / length(vloop.approx.income.total.null)
vloop.valid.exact.income.total.null <- Reduce("+", vloop.exact.income.total.null) / length(vloop.exact.income.total.null)
vloop.valid.income.distribution.null <- Reduce("+", vloop.income.distribution.null) / length(vloop.income.distribution.null)
vloop.valid.exact.income.score.null <- Reduce("+", vloop.exact.income.score.null) / length(vloop.exact.income.score.null)
vloop.valid.approx.income.score.null <- Reduce("+", vloop.approx.income.score.null) / length(vloop.approx.income.score.null)

write.table(round(vloop.valid.approx.income.total.null*100,2), "clipboard", sep="\t", col.names = T)
write.table(round(vloop.valid.approx.income.score.null*100,2), "clipboard", sep="\t", col.names = T)

ttable <- as.matrix(vloop.valid.income.distribution.null) * vloop.valid.approx.income.score.null
rowSums(ttable)
vloop.valid.approx.income.total.null

```



#Pattern Tables 
```{r}
#This table is saying the % of people who answered exactly correctly by each cell (subset of data based on row/column intersection, so the value is based on total number of people who belong to x actual health category and y income bracket)
finaltab<-matrix(NA, nrow=5, ncol=5)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
    test<-valid_data_df$percep_true[valid_data_df$INCGRP_A==i & valid_data_df$score_quant==x] 
    vec1<-sum(test)/length(test)
    finaltab[i,x]<-vec1
  }
}


rownames(finaltab) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(finaltab) <- c("Excellent","Very Good","Good","Fair","Poor")
finaltab<-round((finaltab*100), 2)
#finaltab

#This table is saying the % of people who answered correctly within +/-1 category by each cell (subset of data based on row/column intersection, so the value is based on total number of people who belong to x actual health category and y income bracket)
finaltab2<-matrix(NA, nrow=5, ncol=5)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
    test<-valid_data_df$percep_true_2[valid_data_df$INCGRP_A==i & valid_data_df$score_quant==x] 
    vec1<-sum(test)/length(test)
    finaltab2[i,x]<-vec1
  }
}
rownames(finaltab2) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(finaltab2) <- c("Excellent","Very Good","Good","Fair","Poor")
finaltab2<-round((finaltab2*100), 2)
#finaltab2


#This table is how many responses were exactly correct for each individual perceived category by income bracket. Each cell is saying x% of people in y income category were correct.
finaltab_100<-matrix(NA, nrow=5, ncol=5)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
    test<-valid_data_df$percep_true[valid_data_df$INCGRP_A==i & valid_data_df$score_quant==x] 
    vec1<-sum(test)/nrow(valid_data_df[valid_data_df$INCGRP_A==i,])
    finaltab_100[i,x]<-vec1
  }
}
finaltab_100<-round((finaltab_100*100), 2)
finaltab_100<-cbind(finaltab_100,rowSums(finaltab_100))
rownames(finaltab_100) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(finaltab_100) <- c("Excellent","Very Good","Good","Fair","Poor","Row Total")
#finaltab_100



#This table is how many responses were correct within +/-1 perceieved health category by income bracket Each cell is saying x% of people in y income bracket were correctly within +/-1 perceived health category.
finaltab_100_2<-matrix(NA, nrow=5, ncol=5)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
    test<-valid_data_df$percep_true_2[valid_data_df$INCGRP_A==i & valid_data_df$score_quant==x] 
    vec1<-sum(test)/nrow(valid_data_df[valid_data_df$INCGRP_A==i,])
    finaltab_100_2[i,x]<-vec1
  }
}
finaltab_100_2<-round((finaltab_100_2*100), 2)
finaltab_100_2<-cbind(finaltab_100_2,rowSums(finaltab_100_2))
rownames(finaltab_100_2) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(finaltab_100_2) <- c("Excellent","Very Good","Good","Fair","Poor","Row Total")
#finaltab_100_2

#tables, if true excellent or true poor, row adds up to 100, other col show where inaccuracies went

#table for poor and excellent examining where percent of other choices went

finaltab_excel<-matrix(NA, nrow=5, ncol=5)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
  test<-valid_data_df[valid_data_df$INCGRP_A==i & valid_data_df$score_quant==1,]
  vec1<-nrow(test[test$PHSTAT_A==unique(sort(test$PHSTAT_A, decreasing=F))[x],])/nrow(test)
  finaltab_excel[i,x]<-vec1
  }
}
finaltab_excel<-round((finaltab_excel*100), 2)
rownames(finaltab_excel) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(finaltab_excel) <- c("Excellent","Very Good","Good","Fair","Poor")
#finaltab_excel



finaltab_poor<-matrix(NA, nrow=5, ncol=5)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
  test<-valid_data_df[valid_data_df$INCGRP_A==i & valid_data_df$score_quant==5,]
  vec1<-nrow(test[test$PHSTAT_A==unique(sort(test$PHSTAT_A, decreasing=F))[x],])/nrow(test)
  finaltab_poor[i,x]<-vec1
  }
}
finaltab_poor<-round((finaltab_poor*100), 2)
colnames(finaltab_poor) <- c("Excellent","Very Good","Good","Fair","Poor")
rownames(finaltab_poor) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
#finaltab_poor
```

```{r}
#This table is saying the % of people who answered exactly correctly by each cell (subset of data based on row/column intersection, so the value is based on total number of people who belong to x actual health category and y income bracket)
finaltab
finaltab2
#This table is saying the % of people who answered correctly within +/-1 category by each cell (subset of data based on row/column intersection, so the value is based on total number of people who belong to x actual health category and y income bracket)
finaltab2

#This table is how many responses were exactly correct for each individual perceived category by income bracket. Each cell is saying x% of people in y income category were correct.
finaltab_100



#This table is how many responses were correct within +/-1 perceieved health category by income bracket Each cell is saying x% of people in y income bracket were correctly within +/-1 perceived health category.
finaltab_100_2

#tables, if true excellent or true poor, row adds up to 100, other col show where inaccuracies went
#table for poor and excellent examining where percent of other choices went
finaltab_excel
finaltab_poor
```


#EDA Plots & tables
```{r}
##Income bar chart
ggplot(data = valid_data_df, aes(x=INCGRP_A))+
  geom_bar()+
  xlab("Income Bracket")+
  ylab("Count")+
  theme_minimal()+
  scale_x_discrete(labels=c("1" = "$0-$34,999", "2" = "$35,000-$49,999","3" = "$50,000-$74,999", "4"="$75,000-$99,999", "5"="$100,000+"))

##Perceived bar chart
ggplot(data = valid_data_df, aes(x=PHSTAT_A))+
  geom_bar()+
  xlab("Perceived Health")+
  ylab("Count")+
  theme_minimal()+
  scale_x_discrete(labels=c("1" = "Excellent", "2" = "Very Good","3" = "Good", "4"="Fair", "5"="Poor", "7"="Refused", "9"="Don't Know"))



##Score histogram
ggplot(data = valid_data_df, aes(x=score))+
  theme_minimal()+
  geom_histogram(breaks=seq(0,2.5, by=0.05),color="black", fill="Black")+
  xlab("Score")+
  ylab("Count")

range(valid_data_df$score)


#Perceived health by income
health_inc_tab<-matrix(NA, nrow=5, ncol=5)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$PHSTAT_A))){
    test<-valid_data_df[valid_data_df$INCGRP_A==i,]
    vec1<-nrow(test[test$PHSTAT_A==x,])/nrow(test[test$INCGRP_A==i,])
    health_inc_tab[i,x]<-vec1
  }
}
health_inc_tab<-round((health_inc_tab*100), 2)
rownames(health_inc_tab) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(health_inc_tab) <- c("Excellent","Very Good","Good","Fair","Poor")
#health_inc_tab

#Score quintiles by income
quant_inc_tab<-matrix(NA, nrow=5, ncol=5)
for(i in 1:length(unique(valid_data_df$INCGRP_A))){
  for(x in 1:length(unique(valid_data_df$score_quant))){
    test<-valid_data_df[valid_data_df$INCGRP_A==i,]
    vec1<-nrow(test[test$score_quant==x,])/nrow(test[test$INCGRP_A==i,])
    quant_inc_tab[i,x]<-vec1
  }
}
quant_inc_tab<-round((quant_inc_tab*100), 2)
rownames(quant_inc_tab) <- c("<34,999","35,000-49,999","50,000-74,999","75,000-99,999","100,000+")
colnames(quant_inc_tab) <- c("Excellent","Very Good","Good","Fair","Poor")
#quant_inc_tab
```







